// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type ArticlepageDocumentDataSlicesSlice =
  | ChapterSlice
  | RichTextSlice
  | TableSlice
  | StrategyAccordionSlice;

/**
 * Content for Article Page documents
 */
interface ArticlepageDocumentData {
  /**
   * Slice Zone field in *Article Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: articlepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArticlepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Article Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: articlepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: articlepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articlepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article Page document from Prismic
 *
 * - **API ID**: `articlepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticlepageDocumentData>,
    "articlepage",
    Lang
  >;

type HomePageDocumentDataSlicesSlice = GuidePlaybookHeroSlice;

/**
 * Content for Home page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type TopBarDocumentDataSlicesSlice = VoiceAgentPlaybookSlice;

/**
 * Content for Top bar documents
 */
interface TopBarDocumentData {
  /**
   * Slice Zone field in *Top bar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: top_bar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TopBarDocumentDataSlicesSlice>;
}

/**
 * Top bar document from Prismic
 *
 * - **API ID**: `top_bar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TopBarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TopBarDocumentData>,
    "top_bar",
    Lang
  >;

export type AllDocumentTypes =
  | ArticlepageDocument
  | HomePageDocument
  | TopBarDocument;

/**
 * Item in *Chapter → Default → Primary → Chapter*
 */
export interface ChapterSliceDefaultPrimaryChapterItem {
  /**
   * Chapter title field in *Chapter → Default → Primary → Chapter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: chapter.default.primary.chapter[].chapter_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  chapter_title: prismic.KeyTextField;

  /**
   * Chapter content field in *Chapter → Default → Primary → Chapter*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: chapter.default.primary.chapter[].chapter_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  chapter_content: prismic.RichTextField;
}

/**
 * Primary content in *Chapter → Default → Primary*
 */
export interface ChapterSliceDefaultPrimary {
  /**
   * Chapter field in *Chapter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: chapter.default.primary.chapter[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  chapter: prismic.GroupField<Simplify<ChapterSliceDefaultPrimaryChapterItem>>;
}

/**
 * Default variation for Chapter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChapterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ChapterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Chapter*
 */
type ChapterSliceVariation = ChapterSliceDefault;

/**
 * Chapter Shared Slice
 *
 * - **API ID**: `chapter`
 * - **Description**: Chapter
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChapterSlice = prismic.SharedSlice<
  "chapter",
  ChapterSliceVariation
>;

/**
 * Item in *Home → HomePage → Primary → Learning Outcomes*
 */
export interface GuidePlaybookHeroSliceDefaultPrimaryLearningOutcomesItem {
  /**
   * Outcome Text field in *Home → HomePage → Primary → Learning Outcomes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide_playbook_hero.default.primary.learning_outcomes[].outcome_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  outcome_text: prismic.RichTextField;

  /**
   * Outcome Image field in *Home → HomePage → Primary → Learning Outcomes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: guide_playbook_hero.default.primary.learning_outcomes[].outcome_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  outcome_image: prismic.ImageField<never>;
}

/**
 * Item in *Home → HomePage → Primary → Audience Cards*
 */
export interface GuidePlaybookHeroSliceDefaultPrimaryAudienceCardsItem {
  /**
   * Audience Label field in *Home → HomePage → Primary → Audience Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., P01
   * - **API ID Path**: guide_playbook_hero.default.primary.audience_cards[].audience_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  audience_label: prismic.KeyTextField;

  /**
   * Audience Title field in *Home → HomePage → Primary → Audience Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Product teams
   * - **API ID Path**: guide_playbook_hero.default.primary.audience_cards[].audience_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  audience_title: prismic.KeyTextField;

  /**
   * Audience Description field in *Home → HomePage → Primary → Audience Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guide_playbook_hero.default.primary.audience_cards[].audience_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  audience_description: prismic.RichTextField;
}

/**
 * Primary content in *Home → HomePage → Primary*
 */
export interface GuidePlaybookHeroSliceDefaultPrimary {
  /**
   * Heading field in *Home → HomePage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter main heading
   * - **API ID Path**: guide_playbook_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Home → HomePage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: guide_playbook_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Button field in *Home → HomePage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: guide_playbook_hero.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Table of Contents Heading field in *Home → HomePage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Table of Contents
   * - **API ID Path**: guide_playbook_hero.default.primary.table_of_contents_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  table_of_contents_heading: prismic.KeyTextField;

  /**
   * Learning Section Heading field in *Home → HomePage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., What you'll learn
   * - **API ID Path**: guide_playbook_hero.default.primary.learning_section_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  learning_section_heading: prismic.KeyTextField;

  /**
   * Learning Outcomes field in *Home → HomePage → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: guide_playbook_hero.default.primary.learning_outcomes[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  learning_outcomes: prismic.GroupField<
    Simplify<GuidePlaybookHeroSliceDefaultPrimaryLearningOutcomesItem>
  >;

  /**
   * Audience Section Heading field in *Home → HomePage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Who this playbook is for
   * - **API ID Path**: guide_playbook_hero.default.primary.audience_section_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  audience_section_heading: prismic.KeyTextField;

  /**
   * Audience Cards field in *Home → HomePage → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: guide_playbook_hero.default.primary.audience_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  audience_cards: prismic.GroupField<
    Simplify<GuidePlaybookHeroSliceDefaultPrimaryAudienceCardsItem>
  >;
}

/**
 * HomePage variation for Home Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GuidePlaybookHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GuidePlaybookHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Home*
 */
type GuidePlaybookHeroSliceVariation = GuidePlaybookHeroSliceDefault;

/**
 * Home Shared Slice
 *
 * - **API ID**: `guide_playbook_hero`
 * - **Description**: Hero section for a comprehensive guide/playbook with table of contents, learning outcomes, and audience information
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GuidePlaybookHeroSlice = prismic.SharedSlice<
  "guide_playbook_hero",
  GuidePlaybookHeroSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Rich text field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rich_text: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *Article → Default → Primary → You will learn items*
 */
export interface StrategyAccordionSliceDefaultPrimaryYouWillLearnItemsItem {
  /**
   * Learn item field in *Article → Default → Primary → You will learn items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: strategy_accordion.default.primary.you_will_learn_items[].learn_item
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  learn_item: prismic.KeyTextField;
}

/**
 * Item in *Article → Default → Primary → Chapter*
 */
export interface StrategyAccordionSliceDefaultPrimaryChapterItem {
  /**
   * Chapter title field in *Article → Default → Primary → Chapter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: strategy_accordion.default.primary.chapter[].chapter_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  chapter_title: prismic.KeyTextField;

  /**
   * Chapter content field in *Article → Default → Primary → Chapter*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: strategy_accordion.default.primary.chapter[].chapter_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  chapter_content: prismic.RichTextField;
}

/**
 * Primary content in *Article → Default → Primary*
 */
export interface StrategyAccordionSliceDefaultPrimary {
  /**
   * Part Number field in *Article → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Paste part number
   * - **API ID Path**: strategy_accordion.default.primary.part_number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  part_number: prismic.NumberField;

  /**
   * Part name field in *Article → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Paste part name
   * - **API ID Path**: strategy_accordion.default.primary.part_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  part_name: prismic.KeyTextField;

  /**
   * Part color field in *Article → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Select part theme color
   * - **API ID Path**: strategy_accordion.default.primary.part_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  part_color: prismic.ColorField;

  /**
   * You will learn items field in *Article → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: strategy_accordion.default.primary.you_will_learn_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  you_will_learn_items: prismic.GroupField<
    Simplify<StrategyAccordionSliceDefaultPrimaryYouWillLearnItemsItem>
  >;

  /**
   * Summary description field in *Article → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: strategy_accordion.default.primary.summary_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  summary_description: prismic.KeyTextField;

  /**
   * Chapter field in *Article → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: strategy_accordion.default.primary.chapter[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  chapter: prismic.GroupField<
    Simplify<StrategyAccordionSliceDefaultPrimaryChapterItem>
  >;
}

/**
 * Default variation for Article Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default accordion variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StrategyAccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StrategyAccordionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Article*
 */
type StrategyAccordionSliceVariation = StrategyAccordionSliceDefault;

/**
 * Article Shared Slice
 *
 * - **API ID**: `strategy_accordion`
 * - **Description**: Accordion component displaying expandable strategy sections with titles, descriptions, and badges
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StrategyAccordionSlice = prismic.SharedSlice<
  "strategy_accordion",
  StrategyAccordionSliceVariation
>;

/**
 * Primary content in *Table → Default → Primary*
 */
export interface TableSliceDefaultPrimary {
  /**
   * Table heading field in *Table → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: table.default.primary.table_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  table_heading: prismic.KeyTextField;

  /**
   * Table description field in *Table → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: table.default.primary.table_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  table_description: prismic.RichTextField;

  /**
   * Table data field in *Table → Default → Primary*
   *
   * - **Field Type**: Table
   * - **Placeholder**: *None*
   * - **API ID Path**: table.default.primary.table_data
   * - **Documentation**: https://prismic.io/docs/fields/table
   */
  table_data: prismic.TableField;
}

/**
 * Default variation for Table Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TableSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TableSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Table*
 */
type TableSliceVariation = TableSliceDefault;

/**
 * Table Shared Slice
 *
 * - **API ID**: `table`
 * - **Description**: Table
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TableSlice = prismic.SharedSlice<"table", TableSliceVariation>;

/**
 * Primary content in *TopBar → Default → Primary*
 */
export interface VoiceAgentPlaybookSliceDefaultPrimary {
  /**
   * Header link field in *TopBar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: voice_agent_playbook.default.primary.header_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  header_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * CTA Button field in *TopBar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: voice_agent_playbook.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for TopBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with heading and CTA button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VoiceAgentPlaybookSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VoiceAgentPlaybookSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TopBar → Article page → Primary*
 */
export interface VoiceAgentPlaybookSliceArticlePagePrimary {
  /**
   * CTA Button field in *TopBar → Article page → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: voice_agent_playbook.articlePage.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Article page variation for TopBar Slice
 *
 * - **API ID**: `articlePage`
 * - **Description**: Default variation with heading and CTA button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VoiceAgentPlaybookSliceArticlePage = prismic.SharedSliceVariation<
  "articlePage",
  Simplify<VoiceAgentPlaybookSliceArticlePagePrimary>,
  never
>;

/**
 * Slice variation for *TopBar*
 */
type VoiceAgentPlaybookSliceVariation =
  | VoiceAgentPlaybookSliceDefault
  | VoiceAgentPlaybookSliceArticlePage;

/**
 * TopBar Shared Slice
 *
 * - **API ID**: `voice_agent_playbook`
 * - **Description**: Header section with title and CTA button for Voice Agent Playbook
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VoiceAgentPlaybookSlice = prismic.SharedSlice<
  "voice_agent_playbook",
  VoiceAgentPlaybookSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticlepageDocument,
      ArticlepageDocumentData,
      ArticlepageDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      TopBarDocument,
      TopBarDocumentData,
      TopBarDocumentDataSlicesSlice,
      AllDocumentTypes,
      ChapterSlice,
      ChapterSliceDefaultPrimaryChapterItem,
      ChapterSliceDefaultPrimary,
      ChapterSliceVariation,
      ChapterSliceDefault,
      GuidePlaybookHeroSlice,
      GuidePlaybookHeroSliceDefaultPrimaryLearningOutcomesItem,
      GuidePlaybookHeroSliceDefaultPrimaryAudienceCardsItem,
      GuidePlaybookHeroSliceDefaultPrimary,
      GuidePlaybookHeroSliceVariation,
      GuidePlaybookHeroSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      StrategyAccordionSlice,
      StrategyAccordionSliceDefaultPrimaryYouWillLearnItemsItem,
      StrategyAccordionSliceDefaultPrimaryChapterItem,
      StrategyAccordionSliceDefaultPrimary,
      StrategyAccordionSliceVariation,
      StrategyAccordionSliceDefault,
      TableSlice,
      TableSliceDefaultPrimary,
      TableSliceVariation,
      TableSliceDefault,
      VoiceAgentPlaybookSlice,
      VoiceAgentPlaybookSliceDefaultPrimary,
      VoiceAgentPlaybookSliceArticlePagePrimary,
      VoiceAgentPlaybookSliceVariation,
      VoiceAgentPlaybookSliceDefault,
      VoiceAgentPlaybookSliceArticlePage,
    };
  }
}
