// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomePageDocumentDataSlicesSlice = GuideRoadmapSlice;

/**
 * Content for Home page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

export type AllDocumentTypes = HomePageDocument;

/**
 * Item in *HomePage → Default → Primary → Roadmap Parts → Sections*
 */
export interface GuideRoadmapSliceDefaultPrimaryPartsSectionsItem {
  /**
   * Section Title field in *HomePage → Default → Primary → Roadmap Parts → Sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter section title
   * - **API ID Path**: guide_roadmap.default.primary.parts[].sections[].section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *HomePage → Default → Primary → Roadmap Parts → Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: guide_roadmap.default.primary.parts[].sections[].section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Expanded by default field in *HomePage → Default → Primary → Roadmap Parts → Sections*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: guide_roadmap.default.primary.parts[].sections[].expanded
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  expanded: prismic.BooleanField;
}

/**
 * Item in *HomePage → Default → Primary → Roadmap Parts*
 */
export interface GuideRoadmapSliceDefaultPrimaryPartsItem {
  /**
   * Part Number field in *HomePage → Default → Primary → Roadmap Parts*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: guide_roadmap.default.primary.parts[].part_number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  part_number: prismic.NumberField;

  /**
   * Part Title field in *HomePage → Default → Primary → Roadmap Parts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Strategy
   * - **API ID Path**: guide_roadmap.default.primary.parts[].part_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  part_title: prismic.KeyTextField;

  /**
   * Sections field in *HomePage → Default → Primary → Roadmap Parts*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: guide_roadmap.default.primary.parts[].sections[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  sections: prismic.NestedGroupField<
    Simplify<GuideRoadmapSliceDefaultPrimaryPartsSectionsItem>
  >;
}

/**
 * Primary content in *HomePage → Default → Primary*
 */
export interface GuideRoadmapSliceDefaultPrimary {
  /**
   * Title field in *HomePage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter title
   * - **API ID Path**: guide_roadmap.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *HomePage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter subtitle
   * - **API ID Path**: guide_roadmap.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * CTA Buttons field in *HomePage → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: guide_roadmap.default.primary.cta_buttons
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_buttons: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Roadmap Parts field in *HomePage → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: guide_roadmap.default.primary.parts[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  parts: prismic.GroupField<Simplify<GuideRoadmapSliceDefaultPrimaryPartsItem>>;
}

/**
 * Default variation for HomePage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GuideRoadmapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GuideRoadmapSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomePage*
 */
type GuideRoadmapSliceVariation = GuideRoadmapSliceDefault;

/**
 * HomePage Shared Slice
 *
 * - **API ID**: `guide_roadmap`
 * - **Description**: A comprehensive guide roadmap with title, subtitle, CTA buttons, and multiple numbered parts containing collapsible sections with subsection items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GuideRoadmapSlice = prismic.SharedSlice<
  "guide_roadmap",
  GuideRoadmapSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      AllDocumentTypes,
      GuideRoadmapSlice,
      GuideRoadmapSliceDefaultPrimaryPartsSectionsItem,
      GuideRoadmapSliceDefaultPrimaryPartsItem,
      GuideRoadmapSliceDefaultPrimary,
      GuideRoadmapSliceVariation,
      GuideRoadmapSliceDefault,
    };
  }
}
