// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  guide_playbook_hero: dynamic(() => import("./Home")),
  rich_text: dynamic(() => import("./RichText")),
  strategy_accordion: dynamic(() => import("./Article")),
  table: dynamic(() => import("./Table")),
  voice_agent_playbook: dynamic(() => import("./TopBar")),
};
