import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { createClient } from "@/prismicio";
import TopBar from "@/components/TopBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();
  const topBar = await client.getSingle("top_bar");
  const defaultSlice = topBar.data.slices.find((s) => s.variation === "default");
  const primary = defaultSlice?.primary as Record<string, unknown> | undefined;
  const headerLinks = (primary?.header_link ?? []) as import("@prismicio/client").LinkField[];
  const ctaButton = (primary?.cta_button ?? {}) as import("@prismicio/client").LinkField;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopBar headerLinks={headerLinks} ctaButton={ctaButton} />
        <div className="pt-15">
          {children}
        </div>
      </body>
    </html>
  );
}
